### PR TITLE
Added !obemojify command

### LINKED ISSUE #30: Text to emoji command
[API for conversion](https://funtranslations.com/api/emoji)
**Purpose:** Arguments sent by the user get emojified.
_Steps:_

- Make a file in the bot functions folder(give proper name). This should do the Axios related work.
- Make a file in the commands which will do the final work.
- Command : _!obemojify "text here"_

**P.S.**
If this API doesn't work well let me know, also record a video of this working using loom when making a PR

### PR DESCRIPTION
**Pull request by kailash360**
I have added the ```!obemojify``` command using the API as provided. It will now look like this.

image

Closes #30

### CODE REVIEW

**Comment by hitenSharm** [comment]
Is your node version is 16 or above? The package lock file seems to have some changes. Also make the pr to the dev branch and make the message an emebed.

**Comment by kailash360** [comment]
Yes, my node version is ```16.10.0```. The changes is package-lock.json may have been due to the new dependency I have installed. 
Also, while making PR to dev branch, it shows conflicts. Can you merge the commits of dev into main so that I can set the base to dev after fixing the conflicts?

**Comment by hitenSharm** [comment]
I don't really intend to merge the two branches for quite some time which is why I included the use of dev branch in the updated contribution markdown 😅 
Whatever conflicts that are happening because of the dev branch just accept the changes from dev branch.

**Comment by kailash360** [comment]
I will be then creating a new PR after fixing the conflicts and setting it to the dev branch

**Pull request closed without merging**
